### ISSUE TITLE
Problems to run cross_validation.py

### ISSUE THREAD

**Issue by fegoyo** [LucaCorvitto/RealFaces_w_StableDiffusion#1]
Hi, how are you?

My name is Fernanda and I am trying to understanding your code, as my first part of my Phd, but I have a problem with a cross_validaation.py, because haven't all the files necessary to runvthis code. This code needs some .pth files as 'center_crop_png_best.pth', referring to all the models that you mentioned on your article ('vit', 'vgg16', 'mobilenet', 'xception', 'resnet') with all transform_type = ['resize_only', 'center_crop', 'random_crop', 'random_resized_crop']. So, could you please, upload these files?

**Comment by LucaCorvitto** [comment]
Hi Fernanda!

Since I can not load the files directly on Github due to the size limitation, I will upload them on Google drive in the next days.
I will update the README once I am done.
Let me know if you run into any other problems.

**Comment by fegoyo** [comment]
Hi Luca!

Thanks for your quick answer!

I don't know if you can help me, but on the file binary_classifiers.py, I can't compress the image because isn't possible to find the .DS_STORE file. Probably, I think that this error occur because I am using MacBook m3 pro to test your code and, even watching, a lot of tutorials to disable this file I have this same error. So, could you please upload this file?

**Comment by LucaCorvitto** [comment]
Hi Fernanda!

The model checkpoints have been loaded on the [drive folder](https://drive.google.com/drive/folders/10-n9jY3USb5O_2bh4yUpo1IRPWxe1RIA) inside the folder named "models". Each zip file contains all the checkpoints needed for the cross_validation run (hopefully).
I also updated the README file for more info on how to run the cross_validation.py file. I hope it will be useful and solve the problem.

Regarding your problem with binary_classifier.py, can you please give me other information about the error, like the traceback?
Meanwhile, I will try to run the code again and see what I can do to help you with that.

**Comment by fegoyo** [comment]
Sure! This is my error! I have .DS_Store file on this path, but still it continues with this problem. My python version is: 3.10.13. Thank you so much for help me. 
<img width="876" alt="Captura de Tela 2024-02-27 às 23 38 58" src="https://github.com/LucaCorvitto/RealFaces_w_StableDiffusion/assets/48812007/d5e1167b-2872-464b-bbab-962a184ce295">

**Comment by LucaCorvitto** [comment]
The error seems to be caused by the fact that PIL tries to open `.DS_Store` as it was an image.
The simplest solution should be deleting this file and check if the error persists.
Otherwise, if this file is somewhat necessary in your folder, than you have to filter it out by adding a few lines of code to avoid opening it, and other potential non-image files, in `compress_create` like this:
```
if '.png' not in name:
    continue
img = Image.open(os.path.join(path, name))
```
Let me know if you have any other problem, I'll try to help.

**Comment by fegoyo** [comment]
Thank you so much! I will try to run this code and, if I have another problem, can I tell you? Curiosity ... do you know what base of stylegan3 did you use? I found all of this: 
![Captura de Tela 2024-03-01 às 17 46 49](https://github.com/LucaCorvitto/RealFaces_w_StableDiffusion/assets/48812007/4fbc9ec9-788e-4371-ba4a-31e2a4d850a5)

**Comment by fegoyo** [comment]
@LucaCorvitto Could you please, tell me  what base of stylegan3 did you use? I found all of this:
![Captura de Tela 2024-03-11 às 16 10 45](https://github.com/LucaCorvitto/RealFaces_w_StableDiffusion/assets/48812007/9e2a1e55-7a28-441a-a161-c04a89a6798f)

Thank you!

**Comment by LucaCorvitto** [comment]
Hi Fernanda!

Sorry for my late response, I didn't see your question.
We used the `stylegan3-r-ffhq-1024x1024`, I will add this information also on the readme file.
Good luck with your work!

**Comment by fegoyo** [comment]
Hi Luca! No problem.

Thank you so much for all quick answers. It will help me!
